"""Add ListingImage table

Revision ID: 42141f82ae91
Revises: 1
Create Date: 2025-03-25 21:49:12.638380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42141f82ae91'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('listing', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('listing', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('listing', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('listing', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
    op.alter_column('listing', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('listing', 'created_at')
    op.drop_column('listing', 'status')
    op.drop_table('listing_image')
    # ### end Alembic commands ###
