import { useNavigate } from 'react-router-dom';
// ... existing code ...
const CreateListing = () => {
  const navigate = useNavigate();
  // ... existing code ...
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // ... existing form submission code ...
    try {
      // ... existing API call code ...
      // After successful submission
      navigate('/');  // Redirect to homepage
    } catch (error) {
      // ... existing error handling ...
    }
  };
  // ... existing code ...
}