"""Add pricing_mode to listings

Revision ID: add_pricing_mode
Revises: 66b831172381
Create Date: 2025-04-24 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, text


# revision identifiers, used by Alembic.
revision = 'add_pricing_mode'
down_revision = '66b831172381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('pricing_mode', sa.String(20), nullable=True))
        
        # Update existing records
        op.execute(text("UPDATE listings SET pricing_mode = 'fixed' WHERE pricing_mode IS NULL"))
        
        # Now make it non-nullable with default
        batch_op.alter_column('pricing_mode',
                            existing_type=sa.String(20),
                            nullable=False,
                            server_default=text("'fixed'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('pricing_mode')

    # ### end Alembic commands ### 