"""Add pricing_mode to listings

Revision ID: add_pricing_mode
Revises: 66b831172381
Create Date: 2025-04-24 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_pricing_mode'
down_revision = '66b831172381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_mode', sa.String(20), nullable=False, server_default='fixed'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('pricing_mode')

    # ### end Alembic commands ### 